### ISSUE TITLE
All parameters values on Conversion items are missing

### ISSUE THREAD

**Issue by strogonoff** [isogr/data-extraction-tools#11]
It might seem like `parameters` for our `Conversion` items are missing:

- Here’s an example of a Conversion with params: https://geodetic-staging.isotc211.org/item/d1ad012f-20f0-4833-81ff-7bdf8d18afcf
- However, here’s our YAML (I think this is after last migration script run?): https://github.com/isogr/registry/blob/master/gr-registry/coordinate-ops--conversion/d1ad012f-20f0-4833-81ff-7bdf8d18afcf.yaml

I know we are barely in touch on this lately, but if you have time perhaps you could take a look? Can speak if needed, in recent days I’m available late HKT so probably during work hours European time.

**Comment by stefanomunarini** [comment]
https://github.com/isogr/registry/commit/0a0306361130301a365db61a5216105c0edff25f
