### ISSUE TITLE
Transformation parameter values are missing

### ISSUE THREAD

**Issue by strogonoff** [isogr/data-extraction-tools#12]
Transformation parameters are exported, but their values are all `null`.

Example transformation after exporting to YAML: https://github.com/isogr/registry/blob/master/gr-registry/coordinate-ops--transformation/e8a8214a-0ec7-4416-a88d-981f7e03d790.yaml#L54

The same transformation in Java system: https://geodetic-staging.isotc211.org/item/e8a8214a-0ec7-4416-a88d-981f7e03d790

**Comment by stefanomunarini** [comment]
https://github.com/isogr/registry/commit/33bfea336eb3d0e3ad2f6034f13ff06d85f40414
