### ISSUE TITLE
Missing information source data: author, publisher

### ISSUE THREAD

**Issue by strogonoff** [isogr/data-extraction-tools#7]
Per this screenshot, there is author:

<img width="894" alt="Screenshot 2023-03-27 at 14 53 48" src="https://user-images.githubusercontent.com/292959/227863132-a12a899a-bfda-4c7a-89a6-9c16c69e9c9b.png">

However, YAML doesn’t seem to include the author field on information sources. Grepping the entire repository for “author:” or “Canon” returns nothing…

**Comment by strogonoff** [comment]
I can see `uuid` field exported on information sources in our YAML. Perhaps we can retrieve some of this data by looking up an item related via that uuid.

**Comment by stefanomunarini** [comment]
Done with https://github.com/isogr/data-extraction-tools/commit/6928013d8051f037de7a88ed85297620dd97048f

**Comment by strogonoff** [comment]
Thanks Stefano!
