### ISSUE TITLE
Multiple additions?

### ISSUE THREAD

**Issue by strogonoff** [isogr/data-extraction-tools#9]
cc @stefanomunarini

**Comment by stefanomunarini** [comment]
https://github.com/isogr/data-extraction-tools/commit/55648968b850fcec4dd6c3b2775ce60dd20c3026

**Comment by strogonoff** [comment]
Looking at https://github.com/isogr/registry, branch master, commit `763783`, we still have multiple additions:

- See Transformation 474 (with UUID 7498bd96-eb7c-4156-969e-dfea6143a66d)
  - It appears once in proposal e2d328f7-99c3-4441-986d-7a5605784a20 as addition (as single item)
  - It appears again in proposal 9c3dd6b7-c60f-4a76-8b7d-00680fd898b3 as addition (along with many many other items)
  - Both proposals have the same date and justification, it looks like it’s actually the same proposal?

Or is the fix not applied to that repository?
